# Generated by Django 3.0 on 2021-05-28 17:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_ip', models.CharField(blank=True, max_length=255, null=True)),
                ('mwgt_ip', models.CharField(blank=True, max_length=255, null=True)),
                ('station_active', models.BooleanField(default=False)),
                ('station_name', models.CharField(blank=True, max_length=255, null=True)),
                ('station_name_eng', models.CharField(blank=True, max_length=255, null=True)),
                ('province', models.CharField(blank=True, max_length=255, null=True)),
                ('pbl', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('station_port', models.IntegerField(blank=True, null=True)),
                ('station_status', models.IntegerField(default=0)),
                ('station_password', models.IntegerField(default=123456)),
                ('station_monitor_device', models.IntegerField(default=1)),
                ('alert_via_email', models.IntegerField(default=0)),
                ('alert_via_line', models.IntegerField(default=1)),
                ('masterfield', models.IntegerField(default=1)),
                ('station_enable', models.IntegerField(default=1)),
                ('station_open_time', models.CharField(blank=True, max_length=255, null=True)),
                ('station_close_time', models.CharField(blank=True, max_length=255, null=True)),
                ('station_team_manage', models.CharField(blank=True, max_length=2, null=True)),
                ('remark_1', models.CharField(blank=True, max_length=255, null=True)),
                ('remark_ring', models.CharField(blank=True, max_length=255, null=True)),
                ('timestramp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'สถานี',
                'verbose_name_plural': 'ข้อมูลสถานี',
                'ordering': ('station_name',),
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('team_name', models.CharField(blank=True, max_length=255, null=True)),
                ('line_notify_token', models.CharField(blank=True, max_length=255, null=True)),
                ('line_offical_token', models.CharField(blank=True, max_length=255, null=True)),
                ('remark', models.CharField(blank=True, max_length=255, null=True)),
                ('last_update', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'ทีมงาน',
                'verbose_name_plural': 'ข้อมูลทีมงาน',
                'ordering': ('team',),
            },
        ),
        migrations.CreateModel(
            name='VIS_ip_address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(blank=True, max_length=255, null=True)),
                ('last_update', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'ข้อมูล IP Address',
                'verbose_name_plural': 'รายละเอียด IP Address',
                'ordering': ('ip_address',),
            },
        ),
        migrations.CreateModel(
            name='Store_data_send_line_failed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_id', models.CharField(blank=True, max_length=255, null=True)),
                ('date_failed', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_pass', models.DateTimeField(blank=True, null=True)),
                ('messages', models.TextField(blank=True, null=True)),
                ('status_send', models.CharField(blank=True, max_length=255, null=True)),
                ('last_update', models.DateTimeField(auto_now_add=True)),
                ('site', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Site')),
                ('team_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Team')),
            ],
            options={
                'verbose_name': 'สถานะการส่งแจ้งเตือน',
                'verbose_name_plural': 'ข้อมูลการส่งข้อมูลไม่ผ่านสถานะ',
                'ordering': ('name_id',),
            },
        ),
        migrations.CreateModel(
            name='Status_Error_logger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_id', models.CharField(blank=True, max_length=255, null=True)),
                ('Error_type', models.CharField(blank=True, max_length=255, null=True)),
                ('Error_start', models.DateTimeField(default=django.utils.timezone.now)),
                ('Error_stop', models.DateTimeField(blank=True, null=True)),
                ('Timestramp', models.DateTimeField(auto_now_add=True)),
                ('site', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Site')),
            ],
            options={
                'verbose_name': 'ประวัติ',
                'verbose_name_plural': 'รายละเอียดประวัติ',
                'ordering': ('name_id',),
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_id', models.CharField(blank=True, max_length=255, null=True)),
                ('MWGT_last_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('MWGT_status', models.CharField(blank=True, max_length=255, null=True)),
                ('VIS_last_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('VIS_status', models.CharField(blank=True, max_length=255, null=True)),
                ('RTC', models.CharField(blank=True, max_length=255, null=True)),
                ('DESC', models.CharField(blank=True, max_length=255, null=True)),
                ('DataUnitMap_Status', models.CharField(default='None', max_length=255)),
                ('DataUnitMap_StatusDesc', models.CharField(default='None', max_length=255)),
                ('DataUnitMap_IP', models.CharField(default='None', max_length=255)),
                ('Unit_log_LgAddr', models.CharField(blank=True, max_length=255, null=True)),
                ('Unit_log_address', models.CharField(default='None', max_length=255)),
                ('Unit_GWTypS', models.CharField(blank=True, max_length=255, null=True)),
                ('Unit_sw_location', models.CharField(blank=True, max_length=255, null=True)),
                ('Unit_sw_version', models.CharField(default='None', max_length=255)),
                ('Unit_hw_version', models.CharField(default='None', max_length=255)),
                ('Unit_status_code', models.CharField(default='None', max_length=255)),
                ('Unit_status_desc', models.CharField(default='None', max_length=255)),
                ('NOZZLE_pump_log_address', models.CharField(blank=True, default='None', max_length=255, null=True)),
                ('NOZZLE_num', models.CharField(blank=True, default='None', max_length=255, null=True)),
                ('NOZZLE_status', models.CharField(blank=True, default='None', max_length=255, null=True)),
                ('NOZZLE_SW_Version', models.CharField(blank=True, default='None', max_length=20, null=True)),
                ('NOZZLE_HW_Version', models.CharField(blank=True, default='None', max_length=20, null=True)),
                ('NOZZLE_SN', models.CharField(default='None', max_length=255)),
                ('NOZZLE_Last_conn', models.CharField(default='None', max_length=255)),
                ('NOZZLE_Battery_Status', models.CharField(default='None', max_length=255)),
                ('NOZZLE_Battery_BatPrcnt', models.CharField(default='None', max_length=255)),
                ('Timestramp', models.DateTimeField(auto_now_add=True)),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Site')),
            ],
            options={
                'verbose_name': 'สถานะ',
                'verbose_name_plural': 'ข้อมูลสถานะ',
                'ordering': ('name_id',),
            },
        ),
        migrations.AddField(
            model_name='site',
            name='nozzle_mapping',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.VIS_ip_address'),
        ),
        migrations.AddField(
            model_name='site',
            name='team_support',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Team'),
        ),
        migrations.CreateModel(
            name='Nozzle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pump_log_address', models.IntegerField(blank=True, null=True)),
                ('nozzle_num', models.IntegerField(blank=True, null=True)),
                ('nozzle_status', models.IntegerField(blank=True, null=True)),
                ('log_address', models.IntegerField(blank=True, null=True)),
                ('station_ip', models.CharField(blank=True, max_length=255, null=True)),
                ('data_unit_ip', models.CharField(blank=True, max_length=255, null=True)),
                ('last_update', models.DateTimeField(auto_now_add=True)),
                ('vis_ip_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.VIS_ip_address')),
            ],
            options={
                'verbose_name': 'มือจ่าย',
                'verbose_name_plural': 'ข้อมูลมือจ่าย',
                'ordering': ('vis_ip_address',),
            },
        ),
    ]
