# Generated by Django 3.0 on 2021-05-28 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210528_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='station_team_manage',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
