# Generated by Django 3.0 on 2021-05-28 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20210528_2015'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nozzle',
            old_name='vis_ip_address',
            new_name='vis_ip',
        ),
        migrations.AddField(
            model_name='vis_ip_address',
            name='nozzle_vis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Nozzle'),
        ),
    ]
