# Generated by Django 3.0 on 2021-05-29 09:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20210528_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='station_close_time',
            field=models.TimeField(blank=True, default=datetime.datetime(2021, 5, 29, 9, 44, 15, 300084), null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='station_open_time',
            field=models.TimeField(blank=True, default=datetime.datetime(2021, 5, 29, 9, 44, 15, 300084), null=True),
        ),
    ]
