# Generated by Django 3.0 on 2021-05-29 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20210529_0947'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nozzle',
            options={'ordering': ('vis_ip',), 'verbose_name': 'มือจ่าย', 'verbose_name_plural': 'ข้อมูลมือจ่าย'},
        ),
        migrations.AlterField(
            model_name='site',
            name='station_close_time',
            field=models.TimeField(blank=True, default='23:59:00.0000000', null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='station_open_time',
            field=models.TimeField(blank=True, default='05:00:00.0000000', null=True),
        ),
        migrations.AlterField(
            model_name='vis_ip_address',
            name='nozzle_vis',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
