# Generated by Django 3.0 on 2021-05-29 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20210529_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='nozzle_mapping',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nozzle_vis', to='app.Nozzle'),
        ),
    ]
