# Generated by Django 3.0 on 2021-05-29 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20210529_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='nozzle_mapping',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.VIS_ip_address'),
        ),
    ]
