# Generated by Django 3.0 on 2021-05-30 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20210529_1035'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nozzle',
            options={'ordering': ('site',), 'verbose_name': 'มือจ่าย', 'verbose_name_plural': 'ข้อมูลมือจ่าย'},
        ),
        migrations.RenameField(
            model_name='nozzle',
            old_name='vis_ip',
            new_name='site',
        ),
    ]
