# Generated by Django 3.0 on 2021-05-30 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20210530_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='nozzle',
            name='active_nozzle',
            field=models.BooleanField(default=False),
        ),
    ]
