# Generated by Django 3.0 on 2021-05-30 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_nozzle_active_nozzle'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nozzle',
            options={'ordering': ('log_address', 'pump_log_address'), 'verbose_name': 'มือจ่าย', 'verbose_name_plural': 'ข้อมูลมือจ่าย'},
        ),
    ]
