# Generated by Django 3.0 on 2021-06-06 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20210530_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='name_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
