# Generated by Django 3.0 on 2021-06-06 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20210606_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='BATTERY_status',
            field=models.CharField(default='normal', max_length=255),
        ),
    ]
