# Generated by Django 3.0 on 2021-06-06 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_status_battery_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='BATTERY_status',
        ),
    ]
