# Generated by Django 3.0 on 2021-06-06 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_status_battery_type_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='BATTERY_Type_status',
        ),
    ]
