# Generated by Django 3.0 on 2021-06-06 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_remove_status_battery_type_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='BATTERY_status_check',
            field=models.CharField(default='normal', max_length=255),
        ),
        migrations.AddField(
            model_name='status',
            name='NOZZLE_status_check',
            field=models.CharField(default='online', max_length=255),
        ),
    ]
