# Generated by Django 3.0 on 2021-06-14 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_auto_20210606_2023'),
    ]

    operations = [
        migrations.CreateModel(
            name='battery_status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_stamp', models.DateTimeField(blank=True, null=True)),
                ('mac', models.CharField(blank=True, max_length=255, null=True)),
                ('sn', models.CharField(blank=True, max_length=255, null=True)),
                ('fwtype', models.CharField(blank=True, max_length=255, null=True)),
                ('version', models.CharField(blank=True, max_length=255, null=True)),
                ('devtype', models.CharField(blank=True, max_length=255, null=True)),
                ('din', models.CharField(blank=True, max_length=255, null=True)),
                ('battery_vcclevel', models.CharField(blank=True, max_length=255, null=True)),
                ('battery_level', models.CharField(blank=True, max_length=255, null=True)),
                ('temp', models.CharField(blank=True, max_length=255, null=True)),
                ('fwu', models.CharField(blank=True, max_length=255, null=True)),
                ('site', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Site')),
            ],
            options={
                'verbose_name': 'แบตเตอร์รี่',
                'verbose_name_plural': 'สถานะแบตเตอร์รี่',
                'ordering': ('date_stamp',),
            },
        ),
    ]
