# Generated by Django 3.0 on 2021-06-14 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_battery_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='battery_status',
            name='name_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
