# Generated by Django 3.0 on 2021-06-14 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_battery_status_name_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='NOZZLE_Battery_Status_Volts',
            field=models.CharField(default='3.50', max_length=255),
        ),
    ]
