# Generated by Django 3.0 on 2021-06-15 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_status_nozzle_battery_status_volts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setup_Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_alert_alarm_day', models.IntegerField(blank=True, null=True)),
                ('time_alert_warning_day', models.IntegerField(blank=True, null=True)),
                ('battery_level_alarm_hours', models.FloatField(blank=True, null=True)),
                ('battery_level_low_hours', models.FloatField(blank=True, null=True)),
                ('battery_level_failed_hours', models.FloatField(blank=True, null=True)),
                ('last_update', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'ตั้งค่าการแจ้งเตือน',
                'verbose_name_plural': 'ข้อมูลตั้งค่าการแจ้งเตือน',
                'ordering': ('last_update',),
            },
        ),
    ]
