# Generated by Django 3.0 on 2021-06-15 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_setup_config'),
    ]

    operations = [
        migrations.RenameField(
            model_name='setup_config',
            old_name='battery_level_alarm_hours',
            new_name='battery_level_alarm_volt',
        ),
        migrations.RenameField(
            model_name='setup_config',
            old_name='battery_level_failed_hours',
            new_name='battery_level_failed_volt',
        ),
        migrations.RenameField(
            model_name='setup_config',
            old_name='battery_level_low_hours',
            new_name='battery_level_low_volt',
        ),
        migrations.RenameField(
            model_name='setup_config',
            old_name='time_alert_alarm_day',
            new_name='time_alert_alarm_hours',
        ),
        migrations.RenameField(
            model_name='setup_config',
            old_name='time_alert_warning_day',
            new_name='time_alert_warning_hours',
        ),
    ]
