# Generated by Django 3.0 on 2021-06-15 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_auto_20210615_0843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='NOZZLE_Battery_Status_Volts',
            field=models.FloatField(default=3.5, max_length=255),
        ),
    ]
