# Generated by Django 3.0 on 2021-06-15 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_auto_20210615_1002'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinegroupId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(blank=True, max_length=200, null=True)),
                ('group_id', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'จัดการ Line Group',
                'verbose_name_plural': 'รายละเอียด Line Group',
                'db_table': 'LinegroupId',
            },
        ),
        migrations.AlterModelOptions(
            name='setup_config',
            options={'ordering': ('last_update',), 'verbose_name': 'ตั้งค่าการแจ้งเตือน', 'verbose_name_plural': 'ตั้งค่าการแจ้งเตือน'},
        ),
    ]
