# Generated by Django 3.0 on 2021-06-15 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('app', '0031_auto_20210615_1634'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersanalDetaillogin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('company', models.CharField(choices=[('orpak', 'orpak'), ('Customer', 'customer')], default='JANUARY', max_length=9)),
                ('key_login', models.TextField(blank=True, max_length=6, null=True, unique=True)),
                ('line_id', models.TextField(blank=True, max_length=255, null=True)),
                ('richmenu_id', models.TextField(blank=True, max_length=255, null=True)),
                ('member_status', models.CharField(blank=True, default='none', max_length=255)),
                ('timestramp', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now_add=True)),
                ('group_line_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.LinegroupId')),
                ('user_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
            ],
            options={
                'verbose_name': 'จัดการเข้าใช้งาน Line',
                'verbose_name_plural': 'รายละเอียดการเข้าใช้งาน Line',
                'db_table': 'persanaldetaillogin',
            },
        ),
    ]
