# Generated by Django 3.0 on 2021-06-15 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_auto_20210615_1638'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='linegroupid',
            options={'verbose_name': 'จัดการ Line Group', 'verbose_name_plural': 'ตั้งค่า Line Group'},
        ),
        migrations.AlterModelOptions(
            name='persanaldetaillogin',
            options={'verbose_name': 'จัดการเข้าใช้งาน Line', 'verbose_name_plural': 'ตั้งค่าผู้ใช้งาน Line '},
        ),
        migrations.AlterField(
            model_name='persanaldetaillogin',
            name='line_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='persanaldetaillogin',
            name='richmenu_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
