# Generated by Django 3.0 on 2021-06-15 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_auto_20210615_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persanaldetaillogin',
            name='member_status',
            field=models.BooleanField(default=False),
        ),
    ]
