# Generated by Django 3.0 on 2021-06-15 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_auto_20210615_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='persanaldetaillogin',
            name='line_id_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
