# Generated by Django 3.0 on 2021-06-16 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_persanaldetaillogin_line_id_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status_error_logger',
            options={'ordering': ('name_id',), 'verbose_name': 'ประวัติ', 'verbose_name_plural': 'ข้อมูลประวัติการ error record'},
        ),
        migrations.AddField(
            model_name='persanaldetaillogin',
            name='if_technician',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Team'),
        ),
    ]
