# Generated by Django 3.0 on 2021-06-18 13:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_auto_20210618_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='Timestramp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
