# Generated by Django 3.0 on 2021-06-18 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_auto_20210618_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='Timestramp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
