# Generated by Django 3.0 on 2021-06-19 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_auto_20210618_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='BATTERY_notify_alarm',
            field=models.CharField(default=False, max_length=255),
        ),
        migrations.AddField(
            model_name='status',
            name='BATTERY_notify_low',
            field=models.CharField(default=False, max_length=255),
        ),
        migrations.AddField(
            model_name='status',
            name='NOZZLE_notify_check',
            field=models.CharField(default=False, max_length=255),
        ),
    ]
