# Generated by Django 3.0 on 2021-06-19 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_auto_20210619_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='status_error_logger',
            name='NOZZLE_Battery_Status_Volts',
            field=models.FloatField(default=3.5, max_length=255),
        ),
        migrations.AddField(
            model_name='status_error_logger',
            name='NOZZLE_num',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='status_error_logger',
            name='Unit_log_LgAddr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
