# Generated by Django 3.0 on 2021-06-19 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_auto_20210619_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='status_error_logger',
            name='NOZZLE_SN',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
