# Generated by Django 3.0 on 2021-06-19 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_status_error_logger_nozzle_sn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status_error_logger',
            name='NOZZLE_Battery_Status_Volts',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
    ]
