# Generated by Django 3.0 on 2021-06-20 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_auto_20210619_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='persanaldetaillogin',
            name='need_to_notify',
            field=models.BooleanField(default=False),
        ),
    ]
