# Generated by Django 3.0 on 2021-06-20 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_persanaldetaillogin_need_to_notify'),
    ]

    operations = [
        migrations.AddField(
            model_name='store_data_send_line_failed',
            name='file_save',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='store_data_send_line_failed',
            name='json_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
